name: ğŸœ Code Scanning
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    js-analyse:
        name: ğŸœ Analyse Javascript/Typescript
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.2
              with:
                node-version: 22

            - name: Install and Run Retire.js
              run: |
                npm install -g retire
                npm fund
                retire --path / -v --ignore node_modules